run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gas
    - goconst
    - goimports
    - govet
    - ineffassign
    - megacheck
    - unconvert
    - revive
  fast: false